# Generated by Django 6.0 on 2025-12-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPessoaFisica',
            fields=[
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento_endereco', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('id_cliente_pf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CadastroPessoaJuridica',
            fields=[
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento_endereco', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('id_cliente_pj', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=14, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=14, null=True)),
                ('porte_empresa', models.CharField(blank=True, max_length=6, null=True)),
                ('cod_natureza_juridica', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_atividade_economica', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id_categoria_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_da_categoria', models.CharField(max_length=45)),
                ('descricao_da_categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento_metodo', models.CharField(max_length=20)),
                ('cliente_fisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_pf', to='cadastro.cadastropessoafisica')),
                ('cliente_juridico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_pj', to='cadastro.cadastropessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_produto', models.CharField(max_length=100)),
                ('preco_do_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cadastro.categoriaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='CompraClienteHasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.PositiveIntegerField(default=1)),
                ('compra_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.compracliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.produto')),
            ],
            options={
                'verbose_name': 'Item da Compra',
                'verbose_name_plural': 'Itens da Compra',
                'unique_together': {('compra_cliente', 'produto')},
            },
        ),
    ]
