# Generated by Django 6.0 on 2026-01-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_do_produto',
        ),
        migrations.AddField(
            model_name='compracliente',
            name='frete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco caso não tenha frete.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compraclientehasproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='cadastro.categoriaproduto'),
        ),
        migrations.AlterField(
            model_name='cadastropessoafisica',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastropessoajuridica',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cadastropessoajuridica',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
