# Generated by Django 6.0 on 2026-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_produto_categoria_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'ordering': ['nome_da_categoria'], 'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome_do_produto'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='descricao_da_categoria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome_da_categoria',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='cadastro.categoriaproduto', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_do_produto',
            field=models.CharField(max_length=200, unique=True, verbose_name='Categorias'),
        ),
    ]
