# Generated by Django 6.0.1 on 2026-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_categoriaproduto_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosGraficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grafico', models.CharField(max_length=50)),
                ('dados_json', models.JSONField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dado para Gráfico',
                'verbose_name_plural': 'Dados para Gráficos',
            },
        ),
    ]
