# Generated by Django 6.0 on 2026-01-20 23:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_dadosgraficos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropessoafisica',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cadastropessoafisica',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='A data de nascimento não pode ser anterior a 1900.')]),
        ),
        migrations.AlterField(
            model_name='cadastropessoajuridica',
            name='complemento_endereco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
