# Generated by Django 5.2.7 on 2026-04-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_cadastropessoafisica_complemento_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='compracliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compraclientehasproduto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dadosgraficos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_do_produto',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do Produto'),
        ),
    ]
